<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextoCupon</name>
   <tag></tag>
   <elementGuidId>a8982147-d98a-4033-93bc-6923e05dc9cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='row-title'][contains(.,'mhj8p64w')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wt_sc_single_coupon.wt-single-coupon.stitched_padding.active-coupon.by_shortcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bec441a-a769-490b-8d91-aee10cafc4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wt_sc_single_coupon wt-single-coupon stitched_padding active-coupon by_shortcode</value>
      <webElementGuid>2b8d95a8-d766-43e8-a592-76f1c67fe499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>614</value>
      <webElementGuid>362a8fc6-643f-46ca-99c1-1112428c2b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to apply coupon</value>
      <webElementGuid>b6d8ce5d-223d-4889-af2f-d84e1b2997fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
10%
Cart discount
mhj8p64w
 i 
</value>
      <webElementGuid>7e7c69b4-d3f6-4085-b05d-af3c1e7cf34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-841 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;elementor elementor-841&quot;]/div[@class=&quot;elementor-element elementor-element-50e947f e-flex e-con-boxed e-con&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-de368d3 elementor-widget elementor-widget-shortcode&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-shortcode&quot;]/div[@class=&quot;wt_sc_single_coupon wt-single-coupon stitched_padding active-coupon by_shortcode&quot;]</value>
      <webElementGuid>6d798439-67a2-4fc4-9fb3-6d3d0c6dede5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/div[3]/div/div/div/div/div</value>
      <webElementGuid>08f5e82b-4e6f-4753-a4d8-0006f7b5e95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aquí tienes tu cupón con un descuento del 10% para tu próxima compra'])[1]/following::div[6]</value>
      <webElementGuid>97db2a18-9e6b-4352-ba77-78746de75500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gracias por tu compra'])[2]/following::div[19]</value>
      <webElementGuid>e4ccd862-42b4-4c06-a55c-ed2552b41fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>69bb193f-18df-4965-a0f1-851286d049e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Click to apply coupon' and (text() = '
10%
Cart discount
mhj8p64w
 i 
' or . = '
10%
Cart discount
mhj8p64w
 i 
')]</value>
      <webElementGuid>b9b225da-21c0-44c2-a760-efdd2f957aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
