<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Direcciones</name>
   <tag></tag>
   <elementGuidId>ed8e101c-b2bb-4934-955c-79e2884e2f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.woocommerce-MyAccount-navigation-link.woocommerce-MyAccount-navigation-link--edit-address > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/article/div/div/div/div/nav/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a666165-f8c1-4cb5-a433-1c99028ab50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/mi-cuenta/direccion/</value>
      <webElementGuid>6aa59436-a5d8-4c7e-9220-a3f4c4c25d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direcciones</value>
      <webElementGuid>634548e6-69b5-42a5-86cd-fa19376e1879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;page-area&quot;]/div[@class=&quot;row&quot;]/article[@class=&quot;col-md-12&quot;]/div[@class=&quot;post-464 page type-page status-publish hentry&quot;]/div[@class=&quot;main-content-page single-content&quot;]/div[@class=&quot;single-entry-summary&quot;]/div[@class=&quot;woocommerce&quot;]/nav[@class=&quot;woocommerce-MyAccount-navigation&quot;]/ul[1]/li[@class=&quot;woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--edit-address&quot;]/a[1]</value>
      <webElementGuid>88d8ed4a-517d-47dd-9d68-396dcaccfb6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/article/div/div/div/div/nav/ul/li[5]/a</value>
      <webElementGuid>0fc79d5f-ee1c-4517-999e-be3556f5e8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Direcciones')]</value>
      <webElementGuid>746992b2-8db4-4b1d-8585-a6f9034b2224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargas'])[2]/following::a[1]</value>
      <webElementGuid>cd28205f-f0de-40d4-8a00-f86b01b70c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjetas regalo'])[1]/following::a[2]</value>
      <webElementGuid>d4a62df9-180b-4ff3-9555-1e2cdbdc34c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalles de la cuenta'])[1]/preceding::a[1]</value>
      <webElementGuid>364084c9-535c-4e1b-b2a7-2371c9f29d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/preceding::a[2]</value>
      <webElementGuid>d216b525-bebc-4be8-91ec-cfbd041cee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Direcciones']/parent::*</value>
      <webElementGuid>35519bbc-a68a-4170-8da7-c7a7ea8bd3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://pruebasqafenix.com/mi-cuenta/direccion/')]</value>
      <webElementGuid>51b9d374-81e0-49a5-8629-24d8b5f019e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[5]/a</value>
      <webElementGuid>86277bd6-b007-4e2d-96d4-a8ef62f30f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pruebasqafenix.com/mi-cuenta/direccion/' and (text() = 'Direcciones' or . = 'Direcciones')]</value>
      <webElementGuid>46825eeb-449d-4b39-b1f0-21075a86eb27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
