<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__show-password-input</name>
   <tag></tag>
   <elementGuidId>4eff2fa7-7b0b-42b1-ab7d-b744b1f7bea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.show-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_login']/div/form/p[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>023df0ea-f1b3-4b4a-9b2d-0097f3d2d967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-password-input</value>
      <webElementGuid>702cb1f7-9e76-4161-aeb8-2145b7d5b53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;u-column1 col-1&quot;]/form[@class=&quot;woocommerce-form woocommerce-form-login login&quot;]/p[@class=&quot;woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide&quot;]/span[@class=&quot;password-input&quot;]/span[@class=&quot;show-password-input&quot;]</value>
      <webElementGuid>3a20995d-afc0-4e9d-b007-c6ac18827093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p[2]/span/span</value>
      <webElementGuid>c9d3a5a0-152b-4819-b720-85acfe8eb14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span/span</value>
      <webElementGuid>748fa511-abdd-4d4c-b414-e2477cef7705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
