<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mi Cuenta</name>
   <tag></tag>
   <elementGuidId>a31ea1f7-bf75-41f9-9f31-88e522242907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-642 > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-642']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>383e7d93-ec8d-4149-8bdd-bd644088a7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mi Cuenta</value>
      <webElementGuid>d5b0ef51-3838-461e-8520-666ba7f98870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pruebasqafenix.com/mi-cuenta/</value>
      <webElementGuid>e33a2622-f881-4e82-badc-48205ff512bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>574efeeb-d9c8-4ece-a5a3-fc760a6b09f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mi Cuenta</value>
      <webElementGuid>8e9dfd84-0d9b-4afb-be75-6b9876aeb86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-642&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>7221aab9-5dd5-44b6-98ee-794300cea67a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-642']/a</value>
      <webElementGuid>05fe2d2a-3926-403d-8e7a-60000f2adec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mi Cuenta')]</value>
      <webElementGuid>35fdb5fc-b286-4070-bea1-b31e38e3e46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/following::a[1]</value>
      <webElementGuid>ea38b1e1-7e70-4478-8b1c-1d1e6ba74add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/following::a[3]</value>
      <webElementGuid>b355ce6c-9bc6-4285-9e8d-e0fb3560fe6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW!'])[1]/preceding::a[1]</value>
      <webElementGuid>f9f8ddf5-6e67-4dbc-9db0-476e12de24ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mi Cuenta']/parent::*</value>
      <webElementGuid>69dcca4d-0792-4194-b7b2-cf629c8dbd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://pruebasqafenix.com/mi-cuenta/')])[2]</value>
      <webElementGuid>aa9fc729-c9cf-41e3-98fe-e7b8bfe3a34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>9a9217bf-a413-465b-a352-24d5517c0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Mi Cuenta' and @href = 'https://pruebasqafenix.com/mi-cuenta/' and (text() = 'Mi Cuenta' or . = 'Mi Cuenta')]</value>
      <webElementGuid>c756b028-9806-4d40-b4d3-2e499877e649</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
