<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceptar</name>
   <tag></tag>
   <elementGuidId>519dc31a-aae4-4db3-bfb8-bce2a1b64cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookies-eu-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cookies-eu-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8db28a37-7d3f-4baa-aea1-fa360974b5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookies-eu-accept</value>
      <webElementGuid>0fbe0fea-5a7e-4487-857e-54655f3df423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookies-eu-accept</value>
      <webElementGuid>a043ce51-952e-4f60-9794-e7f9251dad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>e08d961a-2b53-4d25-bb53-ace32cba3161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookies-eu-accept&quot;)</value>
      <webElementGuid>9a4cd0b9-ae29-4d79-a646-65c1658f74e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cookies-eu-accept']</value>
      <webElementGuid>f5a61722-8469-44ca-a769-fbcf20762665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookies-eu-buttons']/button[2]</value>
      <webElementGuid>795e8404-da6b-481e-b755-a3c065e95c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazar'])[1]/following::button[1]</value>
      <webElementGuid>11419f1d-40ed-4c80-8086-af356d3f26f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más información'])[1]/following::button[2]</value>
      <webElementGuid>22db7d2b-ff05-4e0c-9159-de062c6b524f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacidad'])[1]/preceding::button[1]</value>
      <webElementGuid>1999f9f2-65d3-4061-974d-c3ee0a830206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Texte d', &quot;'&quot;, 'origine')])[1]/preceding::button[7]</value>
      <webElementGuid>ffc942b4-d19b-45c4-86fc-edab62b755b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>cb3668bd-3742-4735-9b29-97b8d69826ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5819bcf8-f69d-4f12-8550-d79d72afbba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cookies-eu-accept' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>a340087f-03ed-4736-a514-6a89c518582a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
