<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Seamless test automation, supercharged by AI</name>
   <tag></tag>
   <elementGuidId>973a4ca3-34b4-4157-9ce4-f2ab0ca002fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/section/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.hero_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9fdd3ec9-1566-4f3e-b2f3-cd66d58d526d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hero_title</value>
      <webElementGuid>0fca7516-6b29-43b0-a2b5-e0c4015984bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seamless test automation, supercharged by AI</value>
      <webElementGuid>525f0f50-5417-40bc-9505-e391f0c55f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;hero_section&quot;]/h1[@class=&quot;hero_title&quot;]</value>
      <webElementGuid>a7c05120-ad3a-4d7b-9736-47eaeb28ddc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/h1</value>
      <webElementGuid>71db14eb-b3e7-4a4f-933f-e2a2241a0304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::h1[1]</value>
      <webElementGuid>824c8d1e-0000-4c6e-a5ab-2b2ccf3dbede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::h1[1]</value>
      <webElementGuid>916ead75-146a-4f83-8d53-9987b13a6c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write tests faster, get clearer insights, and improve coverage with an AI-augmented platform.'])[1]/preceding::h1[1]</value>
      <webElementGuid>42c9eceb-8e2f-4fec-9d0b-80d6cc7c6222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seamless test automation,']/parent::*</value>
      <webElementGuid>570dd6a7-f5dc-4b8c-82c0-5f145a810a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b88c0b87-1512-4e98-aee7-bb3fbc7ae89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Seamless test automation, supercharged by AI' or . = 'Seamless test automation, supercharged by AI')]</value>
      <webElementGuid>2f15e20f-dcf8-453e-8f3d-ac7580f21cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
