<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Welcome to My Organization_01</name>
   <tag></tag>
   <elementGuidId>e8d86046-ef21-43dc-991c-6646a34920a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cad2c9e-d407-467a-8e2c-9668709367c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-text</value>
      <webElementGuid>ef119762-fb2d-4992-94a3-0f05af672817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome to My Organization_01</value>
      <webElementGuid>a9997534-fb0b-4190-ae81-8df26682b7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to My Organization_01</value>
      <webElementGuid>6290aec1-40fd-4630-822e-c5667cb1b0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;main-header transition-visible&quot;]/div[@class=&quot;object-summary&quot;]/div[@class=&quot;object-title&quot;]/div[@class=&quot;title-text&quot;]</value>
      <webElementGuid>10ed79fa-32d9-465b-b2c0-d2f1503021b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div/div</value>
      <webElementGuid>861c4039-deb9-4678-9d58-6832ae023346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AC'])[1]/following::div[7]</value>
      <webElementGuid>2351621e-5f20-4610-8189-66773a8d4dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Organization_01'])[1]/following::div[13]</value>
      <webElementGuid>391949b9-0ac6-4f1d-a3f8-1229788585f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Projects'])[1]/preceding::div[4]</value>
      <webElementGuid>de8dac32-e240-42d4-aa5b-4ff0db864380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all projects'])[1]/preceding::div[5]</value>
      <webElementGuid>b1eab251-db5b-4dee-a7db-beb2e4f40e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome to My Organization_01']/parent::*</value>
      <webElementGuid>63fff22d-a632-4900-a00a-4de3ca9c400f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>25e95587-aee4-441f-accf-6d9a1318a0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Welcome to My Organization_01' and (text() = 'Welcome to My Organization_01' or . = 'Welcome to My Organization_01')]</value>
      <webElementGuid>51e09e6d-3d6c-4bc1-addf-cd4b83927267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
