<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or sign in with work email_login</name>
   <tag></tag>
   <elementGuidId>fa84aee3-0875-43b3-9d17-40ab074ec5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0d012a2-7865-4fa3-85fb-cfdf785b9148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-in-btn btn-login</value>
      <webElementGuid>d1983d50-799e-4816-aae2-38ba9e57b38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>5651ec51-9c26-47f5-ae30-c1cf9f05b59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>32b52d6f-8c8b-4ca2-9c4d-43d31c6d4d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>e4716404-dce0-4c47-b5cd-8079f39cd430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-buttons&quot;)/input[@class=&quot;sign-in-btn btn-login&quot;]</value>
      <webElementGuid>e20c1ea4-7a69-47bd-9892-f35678b698f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='login']</value>
      <webElementGuid>3bc5abf9-96af-477d-a9ad-aa4f4bb85bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-form-buttons']/input</value>
      <webElementGuid>e31a5b41-603c-4e02-967e-4d5a8cb6367a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>38157e2a-34a2-4d93-9623-d2826de35ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @type = 'submit']</value>
      <webElementGuid>f5f058d8-791a-4d2e-af24-9b9a8a253696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
